[web]
  title = "Redwood App"
  port = 8910
  apiUrl = "/.redwood/functions"
  includeEnvironmentVariables = ["SENTRY_DSN"]
[api]
  port = 8911
[browser]
  open = true
[generate]
  stories = false
  tests = false
[notifications]
  versionUpdates = ["latest"]
